source/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    IndexView, 
    
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('post/', include('TTE.urls.post_urls')),
    path('title/', include('TTE.urls.title_urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TTE/models.py
from django.db import models
from .helpers.validators import at_least_3
from django.contrib.auth import get_user_model


class Title(models.Model):
    name=models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name='Название продукта'
    )

    def __str__(self) -> str:
        return self.name

    
class Post(models.Model):
    title = models.ForeignKey(
        to=Title,
        on_delete=models.CASCADE,
        null=False, 
        verbose_name='Название'
        )

    description = models.TextField(
        max_length=3000,
        null=True,
        blank=True,
        verbose_name='Описание'
        )

    composition = models.TextField(
        max_length=3000,
        null=True,
        blank=True,
        verbose_name='Состав',
        validators=[at_least_3]
    )

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_DEFAULT,
        default=1,
        null=True,
        verbose_name='Автор',
        related_name='posts'
    )

    tags= models.ManyToManyField(
        'TTE.Tag',
        related_name='posts',
        blank=True,
        verbose_name='Тэги'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    interest_count = models.IntegerField(
        default=0, 
        verbose_name='Количество интересов')


    def __str__(self):
        return f"{self.pk} - {self.title}"

    class Meta:
        permissions = [
            ('can_read_post', 'Can read post')
        ]

class Comment(models.Model):
    text= models.TextField(
        max_length=1000,
        null=False,
        blank=False,
        verbose_name='Комментарий'
    )
    author = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        default="Аноним",
        verbose_name='Автор'
    )
    post = models.ForeignKey(
        'TTE.Post', 
        on_delete=models.CASCADE, 
        related_name='comments', 
        verbose_name='Post'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    update_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата редактирования'
    )

    def __str__(self) -> str:
        return self.text[:20]


class Tag(models.Model):
    name=models.CharField(
        max_length=30,
        verbose_name='Тэг'
    )
    created_at=models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    def __str__(self) -> str:
        return self.name

TTE/views/title_views.py
from django.shortcuts import render, redirect
from ..models import Title
from ..forms import TitleForm
from django.views.generic import View, ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin



class TitleListView(ListView):
    template_name = 'titles/list.html'
    model = Title
    context_object_name = 'titles'
    ordering = ['name']
    paginate_by = 5
    paginate_orphans = 1

    
class TitleCreateView(LoginRequiredMixin,CreateView):
    template_name = 'titles/create.html'
    model = Title 
    form_class = TitleForm
    success_url = reverse_lazy('title_list')


class TitleDeleteView(DeleteView):
    model = Title
    success_url = reverse_lazy('title_list')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class TitleUpdateView(UpdateView):
    model = Title
    template_name = 'titles/update.html'
    form_class = TitleForm
    context_object_name = 'title'
    success_url = reverse_lazy('title_list')
    

templates/titles/create.html
{% extends 'base.html'%}

{% block content%}
    <h1>Создать Пост</h1>
    <form action="{%url 'title_create'%}" method="POST">
        {% include 'partials/create_update_form.html' with button_text="Создать" %}
    </form>
{% endblock %}

templates/titles/list.html
{% extends 'base.html' %}
{% load static %}


{% block css %} 
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block content %}
   
   
    <div class="list-group mt-5">
        {% for title in titles %}
                <ul class="list-group mb-3">
                    <li class="list-group-item list-group-item-action d-flex justify-content-between">
                        <div>{{title}}</div>
                        <div>
                            {% if perms.TTE.change_title %}
                                <a href="{% url 'title_update' title.pk %}" class="btn btn-outline-primary btn-sm">
                                    Редактировать
                                </a>
                            {%endif%}
                            {% if perms.TTE.delete_title %}
                                <a href="{% url 'title_delete' title.pk %}" class="btn btn-outline-danger btn-sm">
                                    Удалить
                                </a>
                            {%endif%}
                        </div>
                    </li>
 
                </ul>
        {%endfor%}
    </div>
    {% include 'partials/pagination.html'%}
   
{%endblock%}

templates/titles/update.html
{% extends 'base.html'%}

{% block content%}
    <h1>Создать Пост</h1>
    <form action="{%url 'title_update' title.pk %}" method="POST">
        {% include 'partials/create_update_form.html' with button_text="Редактировать" %}
    </form>
{% endblock %}